docs: add note about stable levski branch
edgexfoundry-holding/device-onvif-camera pull request #272
Opened 2023-03-16 23:28 UTC by ajcasagrande

**If your build fails**  due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-go/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [X] I am not introducing a new dependency (add notes below if you are)
- [N/A] I have added unit tests for the new feature or bug fix (if not, why?)
- [N/A] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [N/A] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

## Testing Instructions

Also back-ported @ChristianDarr-personal 's NATs docs changes

## New Dependency Instructions (If applicable)

2023-03-17 20:50 UTC, presatish requested changes

2023-03-17 20:50 UTC, presatish commented on doc/guides/SimpleStartupGuide.md
Under `Get the source code` https://github.com/EdgeX-Camera-Management/device-onvif-camera/blob/levski-note/doc/guides/SimpleStartupGuide.md#get-the-source-code I think we should also add a note or ask the user to get `levski` version of the device-onvif-camera directory based on the version of edgex-compose used. Need to do the same in CustomStartupGuide.md

2023-03-17 20:50 UTC, presatish commented on doc/running-guide.md
Also in this file there is no mention of `levski` branch. This seems to be the file that might be reached a lot because of https://github.com/EdgeX-Camera-Management/device-onvif-camera/tree/levski-note#getting-started (via the first point)

2023-03-17 21:51 UTC, ChristianDarr-personal requested changes

2023-03-17 21:51 UTC, ChristianDarr-personal commented on doc/guides/CustomStartupGuide.md
> +      Note: The `levski` branch is the latest stable branch at the time of this update.
This should be converted to the nee note style.

2023-03-17 21:51 UTC, ChristianDarr-personal commented on doc/guides/CustomStartupGuide.md
> +>**NOTE:** Go version 1.18+ is required to run natively. See [here](https://go.dev/doc/install) for more information.
Remove the colon to get beautified note

2023-03-20 21:04 UTC, ChristianDarr-personal approved these changes
Looks good pending small changes.

2023-03-21 16:41 UTC, presatish approved these changes

2023-03-21 16:54 UTC, merged