Remove docs
edgexfoundry-holding/device-onvif-camera pull request #305
Opened 2023-04-12 22:20 UTC by ChristianDarr-personal

**If your build fails**  due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-go/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?) - N/A
- [ ] I have fully tested (add details below) this the new feature or bug fix (if not, why?) - N/A
- [x] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

## Testing Instructions

## New Dependency Instructions (If applicable)

2023-04-17 21:12 UTC, lenny-intel requested changes

2023-04-17 21:12 UTC, lenny-intel commented on README.md
> -[Supported ONVIF features](./doc/ONVIF-protocol.md)
Shouldn't the above sections bee remove also and just reference the Docs. Guide links above are broken.

2023-04-18 15:46 UTC, lenny-intel submitted a review, later dismissed
LGTM

2023-05-01 17:40 UTC, presatish approved these changes

2023-05-01 17:42 UTC, presatish approved these changes

2023-05-01 18:50 UTC, merged