fix: remove gofrs-uuid
edgexfoundry-holding/device-onvif-camera pull request #94
Opened 2022-06-29 16:49 UTC by ajcasagrande

Signed-off-by: Anthony Casagrande <anthony.j.casagrande@intel.com>

`github.com/gofrs/uuid` is still an indirect dependency due to onvif library.

See: https://github.com/IOTechSystems/onvif/pull/12

2022-06-29 22:06 UTC, lenny-intel approved these changes, later dismissed
LGTM

2022-06-30 02:14 UTC, cloudxxx8 requested changes
LGTM
thanks for modifying the onvif library, too
sorry, I didn't realize there is a dependency there 
I've merge your PR and tag it as v0.1.2
could you please also update the onvif version to v0.1.2 in this PR, and we can get rid of github.com/gofrs/uuid

2022-06-30 02:25 UTC, ajcasagrande commented
@cloudxxx8 no worries. Done.

2022-06-30 02:38 UTC, cloudxxx8 approved these changes
LGTM

2022-06-30 02:38 UTC, merged